package com.loreal.clock;

import com.azure.cosmos.implementation.uuid.UUIDType;
import com.azure.cosmos.implementation.uuid.impl.UUIDUtil;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.UUID;

public class Fields {
    public static void main(String[] args) {
       UUID s = UUIDUtil.constructUUID(UUIDType.RANDOM_BASED,0, 100);
       System.out.println(s);
       System.out.println(UUIDUtil.constructUUID(UUIDType.RANDOM_BASED,new Random().nextInt(), 100));
       System.out.println(UUIDUtil.constructUUID(UUIDType.RANDOM_BASED,100, 1000));
       System.out.println(UUIDUtil.constructUUID(UUIDType.RANDOM_BASED,99999, 99999));
       System.out.println(UUIDUtil.constructUUID(UUIDType.TIME_BASED,0, 0));
       System.out.println(UUIDUtil.constructUUID(UUIDType.NAME_BASED_SHA1,0, 0));
//       System.out.println(UUIDUtil.constructUUID(UUIDType.RANDOM_BASED,100, 100));
//       System.out.println(UUIDUtil.constructUUID(UUIDType.RANDOM_BASED,100, 100));

    }
    public static String[] orderLayerOne = new String[] {
            "pic_path",
            "payment",
            "snapshot_url",
            "seller_rate",
            "post_fee",
            "receiver_state",
            "consign_time",
            "available_confirm_fee",
            "received_payment",
            "timeout_action_time",
            "tid",
            "num",
            "num_iid",
            "status",
            "title",
            "type",
            "price",
            "discount_fee",
            "has_post_fee",
            "total_fee",
            "created",
            "pay_time",
            "modified",
            "end_time",
            "buyer_message",
            "buyer_memo",
            "seller_memo",
            "step_trade_status",
            "step_paid_fee",
            "buyer_open_uid",
            "shipping_type",
            "adjust_fee",
            "trade_from",
            "can_rate",
            "buyer_rate",
            "seller_can_rate",
            "receiver_city",
            "seller_nick",
            "expand_card_basic_price",
            "expand_card_expand_price",
            "expand_card_basic_price_used",
            "expand_card_expand_price_used",
            "is_part_consign",
            "rx_audit_status",
            "coupon_fee",
            "ouid",
            "seller_flag"
    };
    public static String[] orderOrder = new String[] {
            "pic_path",
            "refund_status",
            "outer_iid",
            "snapshot_url",
            "timeout_action_time",
            "buyer_rate",
            "seller_rate",
            "cid",
            "oid",
            "status",
            "title",
            "price",
            "num_iid",
            "sku_id",
            "num",
            "outer_sku_id",
            "order_from",
            "total_fee",
            "payment",
            "discount_fee",
            "adjust_fee",
            "sku_properties_name",
            "refund_id",
            "is_oversold",
            "end_time",
            "consign_time",
            "shipping_type",
            "logistics_company",
            "invoice_no",
            "divide_order_fee",
            "part_mjz_discount",
            "bind_oids",
            "expand_card_expand_price_used_suborder",
            "expand_card_basic_price_used_suborder",
            "item_meal_id",
            "customization"
    };

    public static String[] orderPromotion = new String[] {
            "id",
            "promotion_name",
            "discount_fee",
            "gift_item_name",
            "gift_item_id",
            "gift_item_num",
            "promotion_desc",
            "promotion_id"
    };
    public static String[] returnFields = new String [] {
            "shipping_type",
            "cs_status",
            "advance_status",
            "split_taobao_fee",
            "split_seller_fee",
            "refund_id",
            "tid",
            "oid",
            "alipay_nototal_fee",
            "buyer_nick",
            "seller_nick",
            "created",
            "modified",
            "order_status",
            "status",
            "good_status",
            "has_good_return",
            "refund_fee",
            "payment",
            "reason",
            "desc",
            "title",
            "price",
            "num",
            "good_return_time",
            "company_name",
            "sid",
            "address",
            "num_iid",
            "refund_phase",
            "refund_version",
            "sku",
            "attribute",
            "outer_id",
            "operation_constraint",
            "buyer_open_uid",
            "ouid"
    };

    public static String[] itemLayerOne = new String[] {
            "detail_url",
            "num_iid",
            "title",
            "nick",
            "type",
            "cid",
            "seller_cids",
            "props",
            "input_pids",
            "input_str",
            "desc",
            "pic_url",
            "num",
            "valid_thru",
            "list_time",
            "delist_time",
            "stuff_status",
            //"location",
            "price",
            "post_fee",
            "express_fee",
            "ems_fee",
            "has_discount",
            "freight_payer",
            "has_invoice",
            "has_warranty",
            "has_showcase",
            "modified",
            "increment",
            "auto_repost",
            "approve_status",
            "postage_id",
            "product_id",
            "auction_point",
            "property_alias",
            //"item_imgs"
            //"prop_imgs"
            "outer_id",
            "is_virtual",
            "is_taobao",
            "is_ex",
            "is_timing",
            //"videos",
            "is_3D",
            "score",
            "volume",
            "one_station",
            "second_kill",
            "auto_fill",
            "cod_postage_id",
            "is_prepay",
            "ww_status",
            "wap_detail_url",
            "wap_desc",
            "sell_promise",
            "period_sold_quantity",
            //"item_rectangle_imgs"
            "violation",
            "barcode",
            "created",
            "after_sale_id",
            "custom_made_type_id",
            "desc_module_info",
            "features",
            "food_security",
            "inner_shop_auction_template_id",
            "is_fenxiao",
            "is_lightning_consignment",
            "is_xinpin",
            "is_area_sale",
            "large_screen_image_url",
            "cuntao_item_specific",
            "desc_modules",
            "with_hold_quantity",
            "wireless_desc",
            "video_id",
            "template_id",
            "sub_stock",
            "sold_quantity",
            "sell_point",
            "props_name",
            "promoted_service",
            "paimai_info",
            "outer_shop_auction_template_id",
            "newprepay",
            "mpic_video",
            "locality_life",
            "item_weight",
            "cpv_memo",
            "global_stock_country",
            "item_size",
            "global_stock_type"
    };

    public static String[] itemSkus = new String[] {
            "sku_id",
            "iid",
            "num_iid",
            "properties",
            "quantity",
            "price",
            "created",
            "modified",
            "status",
            "properties_name",
            "sku_spec_id",
            "with_hold_quantity",
            "sku_delivery_time",
            "outer_id",
            "barcode",
            "gmt_modified",
            "sku_feature",
            "delivery_time_type",
            "spec_id"
    };
}
